services:
  # Database
  postgres:
    image: postgres:16
    container_name: app-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # any tables created via db push are physically saved into local, `data` folder on my hard drive

  # API
  api:
    build:
      context: .
      target: build # not worried about running in js yet
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app # Sync local to the container when files are saved
      - /app/node_modules # Protects container's node_modules from being overwritten
    command: npx tsx watch src/server.ts # waching file changes

volumes:
  postgres_data:
