/// <reference types="node" />
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import dotenv from"dotenv";

if (!process.env.CI) {
  dotenv.config();
}

if (process.env.CI) {
  console.log("--- CI ENVIRONMENT DETECTED ---");
  console.log("DATABASE_URL present:", !!process.env.DATABASE_URL);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.LOCAL_DATABASE_URL || process.env.DATABASE_URL
  },
});
